---

- name: Make sure old transmission is not running nor working
  service:
    name: transmission-daemon
    state: stopped
    enabled: no
  when: ansible_connection != "docker"

- name: Make sure transmission is not running
  service:
    name: custom-transmission-daemon
    state: stopped
  ignore_errors: yes
  when: ansible_connection != "docker"

- name: chown transmission lib directory
  file:
    path: /var/lib/transmission-daemon/.config/transmission-daemon
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    recurse: yes

- name: rm current symbol link
  file:
    path: /var/lib/transmission-daemon/.config/transmission-daemon/settings.json
    state: absent

- name: Copy Transmission configuration
  template:
    src: etc/transmission-daemon/settings.json.j2
    dest: /var/lib/transmission-daemon/.config/transmission-daemon/settings.json
    force: yes
    backup: yes
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"

- name: Copy Transmission configuration
  template:
    src: etc/transmission-daemon/settings.json.j2
    dest: /var/lib/transmission-daemon/settings.json
    force: yes
    backup: yes
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"

- name: Test downloads folder
  command: "ls {{ transmission_download_dir }}"
  register: ls_transmission_download_dir
  ignore_errors: true

- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission_download_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  when: ls_transmission_download_dir.rc != 0

- name: Add watch dir
  file:
    state: directory
    path: "{{ transmission_watch_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  when: transmission_watch_dir_enabled

- name: Test incomplete folder
  command: "ls {{ transmission_incomplete_dir }}"
  register: ls_transmission_incomplete_dir
  ignore_errors: true
  when: transmission_incomplete_dir_enabled

- name: Add incomplete folder
  file:
    state: directory
    path: "{{ transmission_incomplete_dir }}"
    owner: "{{ transmission_user }}"
    group: "{{ transmission_group }}"
    mode: 0775
  when: transmission_incomplete_dir_enabled and ls_transmission_incomplete_dir.rc != 0
