---

- name: Install Transmission
  apt:
    name: transmission-daemon
    state: present
  when: transmission_do_install

- name: Config Transmission
  include: config.yml
  when: transmission_do_config

- name: Deploy Transmission
  include: deploy.yml
  when: transmission_do_depoy and ansible_connection != "docker"
