---
# Installation
- name: Install Transmission
  apt:
    name: transmission-daemon
    state: present

# Configuration
- name: Make sure transmission is not running
  service:
    name: transmission-daemon
    state: stopped

- name: chown transmission lib directory
  file:
    path: /var/lib/transmission-daemon/.config/transmission-daemon
    owner: "{{ transmission_user }}"
    group: debian-transmission
    recurse: yes

- name: Test downloads folder
  command: "ls {{ transmission_download_dir }}"
  register: ls_transmission_download_dir
  ignore_errors: true

- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission_download_dir }}"
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: 0775
  when: ls_transmission_download_dir.rc != 0

- name: Add watch dir
  file:
    state: directory
    path: "{{ transmission_watch_dir }}"
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: 0775
  when: transmission_watch_dir_enabled

- name: Test incomplete folder
  command: "ls {{ transmission_incomplete_dir }}"
  register: ls_transmission_incomplete_dir
  ignore_errors: true

- name: Add incomplete folder
  file:
    state: directory
    path: "{{ transmission_incomplete_dir }}"
    owner: "{{ transmission_user }}"
    group: debian-transmission
    mode: 0775
  when: transmission_incomplete_dir_enabled and ls_transmission_incomplete_dir.rc != 0

- name: Copy Transmission configuration
  template:
    src: etc/transmission-daemon/settings.json.j2
    dest: /etc/transmission-daemon/settings.json

- name: Add current user to transmission group
  user:
    name: "{{ transmission_user }}"
    groups: debian-transmission
    append: yes

# Service start
- name: Start transmission
  service:
    name: transmission-daemon
    state: started
