---
# Installation
- name: Install Transmission
  apt:
    name: transmission-daemon
    state: present
  when: transmission_install

- name: Config Transmission
  include: config.yml
  when: transmission_config

- name: Deploy Transmission
  include: deploy.yml
  when: transmission_deploy
